packages:
  - apps/*
  - apps/newsletter/packages/*
  - packages/*

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
  workerd: true

overrides:
  esbuild: 0.28.1
  postcss: 8.5.10
  yaml: 2.8.3
