/// <reference types="astro/client" />

// Cloudflare bindings live in worker-configuration.d.ts (generated by
// `pnpm generate-types`). Secrets aren't inferred, so declare them here.
// `cloudflare:workers` env resolves against the `Cloudflare.Env` interface.
declare namespace Cloudflare {
  interface Env {
    DEPLOYED_AT?: string;
    DEPLOY_ID?: string;
    DEPLOY_SOURCE?: string;
    GIT_SHA?: string;
    AMA_IP_SALT?: string;
    LIST_API_TOKEN: string;
    LIST_API_URL?: string;
  }
}
